Repository DIT112-V21/group-04, pull requests merged in 2021-05, with the labels that each got.

#37 Fix bug where car makes a sharp right when stopping.
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
Labels: Bug fix, Sprint 2

#41 Fix bug where connection between app and car is not terminated when exiting the joystick menu.
  android/app/src/main/java/com/example/medcarapp/MainActivity.java
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  arduino/smartcar/smartcar.ino
Labels: Bug fix

#39 Update readme and github workflow
  .github/workflows/arduino-build.yml
  README.md
Labels: Sprint 2, documentation

#42 Joystick feedback
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  android/app/src/main/res/layout/activity_manual_control.xml
Labels: Sprint 3

#44 Improve UI toast messages
  android/app/build.gradle
  android/app/src/main/java/com/example/medcarapp/Adapter.java
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  android/app/src/main/java/mqttController/CarConnect.java
  android/app/src/main/res/layout/activity_main.xml
Labels: Sprint 3, improvement

#45 Camera stream
  .gitignore
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  android/app/src/main/java/mqttController/CarConnect.java
  android/app/src/main/res/drawable-v24/carcam.png
  android/app/src/main/res/drawable/intermission.png
  android/app/src/main/res/layout/activity_manual_control.xml
  arduino/smartcar/smartcar.ino
Labels: Sprint 3

#50 Car selection check to enable button
  android/app/src/main/java/com/example/medcarapp/Adapter.java
  android/app/src/main/java/com/example/medcarapp/MainActivity.java
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/values/colors.xml
Labels: Sprint 3, improvement

#51 Landscape view
  android/app/src/main/java/com/example/medcarapp/Adapter.java
  android/app/src/main/java/mqttController/CarConnect.java
  android/app/src/main/res/layout-land/activity_main.xml
  android/app/src/main/res/layout-land/activity_manual_control.xml
Labels: Feature, Sprint 3

#53 Autonomous driving and Autonomous driving status
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  android/app/src/main/java/mqttController/CarConnect.java
  android/app/src/main/res/layout/activity_manual_control.xml
  arduino/smartcar/smartcar.ino
Labels: Feature, Sprint 3

#61 Server selection
  README.md
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/medcarapp/Adapter.java
  android/app/src/main/java/com/example/medcarapp/IntroductoryActivity.java
  android/app/src/main/java/com/example/medcarapp/MainActivity.java
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  android/app/src/main/java/com/example/medcarapp/ServerAdapter.java
  android/app/src/main/java/com/example/medcarapp/ServerSelection.java
  android/app/src/main/java/mqttController/CarConnect.java
  android/app/src/main/java/mqttController/MqttClient.java
  android/app/src/main/res/drawable/offline.png
  android/app/src/main/res/drawable/online.png
  android/app/src/main/res/layout-land/server_selection.xml
  android/app/src/main/res/layout/server_rows.xml
  android/app/src/main/res/layout/server_selection.xml
  android/app/src/main/res/values/strings.xml
  arduino/smartcar/smartcar.ino
Labels: Sprint 3

#62 Obstacle notification
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/mqttController/CarConnect.java
  android/app/src/main/java/vibrator/VibratorWrapper.java
  arduino/smartcar/smartcar.ino
Labels: Feature, Sprint 3

#63 Refactor output text/strings code
  android/app/src/main/java/com/example/medcarapp/Adapter.java
  android/app/src/main/java/com/example/medcarapp/MainActivity.java
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  android/app/src/main/java/mqttController/CarConnect.java
  android/app/src/main/res/layout-land/activity_main.xml
  android/app/src/main/res/layout-land/activity_manual_control.xml
  android/app/src/main/res/layout-land/server_selection.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/activity_manual_control.xml
  android/app/src/main/res/layout/credit_popup.xml
  android/app/src/main/res/layout/recycle_view_rows.xml
  android/app/src/main/res/layout/server_rows.xml
  android/app/src/main/res/layout/server_selection.xml
  android/app/src/main/res/values/strings.xml
Labels: Refactor, Sprint 3

#67 Auto button bug fix
  android/app/src/main/java/com/example/medcarapp/MainActivity.java
  android/app/src/main/res/layout-land/activity_manual_control.xml
Labels: Bug fix, Sprint 4

#71 Joystick update
  android/app/src/main/res/drawable-v24/joystickbackground3.png
  android/app/src/main/res/drawable-v24/joystickbutton3.png
  android/app/src/main/res/drawable/joystickbg.png
  android/app/src/main/res/drawable/joystickbutton1.png
  android/app/src/main/res/layout-land/activity_manual_control.xml
  android/app/src/main/res/layout/activity_manual_control.xml
Labels: Sprint 4, improvement

#72 Enhanced autonomous driving
  arduino/smartcar/smartcar.ino
Labels: Sprint 4, enhancement

#73 Improve Speedometer layout
  android/app/build.gradle
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  android/app/src/main/res/layout-land/activity_manual_control.xml
  android/app/src/main/res/layout/activity_manual_control.xml
  android/app/src/main/res/values/colors.xml
Labels: Sprint 4, improvement

#78 Removal of unused imports
  android/app/src/main/java/com/example/medcarapp/MainActivity.java
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
Labels: Sprint 4, improvement

#80 Android Unit Tests
  android/app/build.gradle
  android/app/src/androidTest/java/com/example/medcarapp/DrawableMatcher.java
  android/app/src/androidTest/java/com/example/medcarapp/ExampleInstrumentedTest.java
  android/app/src/androidTest/java/com/example/medcarapp/IntroductoryActivityTest.java
  android/app/src/androidTest/java/com/example/medcarapp/MainActivityTest.java
  android/app/src/androidTest/java/com/example/medcarapp/ManualControlTest.java
  android/app/src/androidTest/java/com/example/medcarapp/RecyclerViewMatcher.java
  android/app/src/androidTest/java/com/example/medcarapp/ServerSelectionTest.java
  android/app/src/androidTest/java/com/example/medcarapp/ToastMatcher.java
  android/app/src/main/java/com/example/medcarapp/CarAdapter.java
  android/app/src/main/java/com/example/medcarapp/IntroductoryActivity.java
  android/app/src/main/java/com/example/medcarapp/MainActivity.java
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  android/app/src/main/java/com/example/medcarapp/ServerAdapter.java
  android/app/src/main/java/com/example/medcarapp/ServerSelection.java
  android/app/src/main/java/mqttController/CarConnect.java
  android/app/src/main/java/mqttController/MqttClient.java
  android/app/src/main/res/values/strings.xml
Labels: Feature, Sprint 4

#79 #60 Update security description
  README.md
Labels: High, Sprint 4, documentation

#83 Finalizing code, improvements and refactoring
  .gitignore
  android/app/src/main/java/com/example/medcarapp/CarAdapter.java
  android/app/src/main/java/com/example/medcarapp/MainActivity.java
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  android/app/src/main/java/com/example/medcarapp/ServerAdapter.java
  android/app/src/main/java/com/example/medcarapp/ServerSelection.java
  android/app/src/main/java/mqttController/CarConnect.java
  android/app/src/main/java/vibrator/VibratorWrapper.java
  arduino/cmake-build-debug/CMakeCache.txt
  arduino/cmake-build-debug/CMakeFiles/3.20.2/CMakeCCompiler.cmake
  arduino/cmake-build-debug/CMakeFiles/3.20.2/CMakeCXXCompiler.cmake
  arduino/cmake-build-debug/CMakeFiles/3.20.2/CMakeDetermineCompilerABI_C.bin
  arduino/cmake-build-debug/CMakeFiles/3.20.2/CMakeDetermineCompilerABI_CXX.bin
  arduino/cmake-build-debug/CMakeFiles/3.20.2/CMakeSystem.cmake
  arduino/cmake-build-debug/CMakeFiles/3.20.2/CompilerIdC/CMakeCCompilerId.c
  arduino/cmake-build-debug/CMakeFiles/3.20.2/CompilerIdCXX/CMakeCXXCompilerId.cpp
  arduino/cmake-build-debug/CMakeFiles/CMakeError.log
  arduino/cmake-build-debug/CMakeFiles/CMakeOutput.log
  arduino/cmake-build-debug/CMakeFiles/clion-environment.txt
  arduino/cmake-build-debug/CMakeFiles/clion-log.txt
  arduino/cmake-build-debug/CMakeFiles/cmake.check_cache
  arduino/cmake-build-debug/test/googletest-release-1.10.0/googletest/generated/GTestConfig.cmake
  arduino/cmake-build-debug/test/googletest-release-1.10.0/googletest/generated/GTestConfigVersion.cmake
  arduino/cmake-build-debug/test/googletest-release-1.10.0/googletest/generated/gmock.pc
  arduino/cmake-build-debug/test/googletest-release-1.10.0/googletest/generated/gmock_main.pc
  arduino/cmake-build-debug/test/googletest-release-1.10.0/googletest/generated/gtest.pc
  arduino/cmake-build-debug/test/googletest-release-1.10.0/googletest/generated/gtest_main.pc
  arduino/sketches/NonTestableSmartcar/NonTestableSmartcar.ino
  arduino/sketches/smartcar/BackDistanceSensorImplementation.h
  arduino/sketches/smartcar/Car.h
  arduino/sketches/smartcar/FrontDistanceSensorImplementation.h
  arduino/sketches/smartcar/MQTTinterface.h
  arduino/sketches/smartcar/SerialImplementation.h
  arduino/sketches/smartcar/SimpleCarController.h
  arduino/sketches/smartcar/SimpleCarMqttImplementation.h
  arduino/sketches/smartcar/SimpleCarWrapper.h
  arduino/sketches/smartcar/smartcar.ino
  arduino/test/mocks/MockCar.h
  arduino/test/ut/SimpleCarController_test.cpp
Labels: Bug fix, Sprint 4, improvement
