Repository DIT112-V21/group-04, pull requests merged in 2021-04, with the labels that each got.

#9 Setup car obstacle avoidance - Assignment1
  Assignment1/obsAvoidance/obsAvoidance.ino
Labels: Sprint 1

#12 Set up CI for android app
  .github/workflows/android-ci.yml
Labels: Sprint 1

#20 Android app UI
  android/.gitignore
  android/.idea/.gitignore
  android/.idea/.name
  android/.idea/compiler.xml
  android/.idea/gradle.xml
  android/.idea/jarRepositories.xml
  android/.idea/misc.xml
  android/.idea/vcs.xml
  android/app/.gitignore
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/androidTest/java/com/example/medcarapp/ExampleInstrumentedTest.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/medcarapp/Adapter.java
  android/app/src/main/java/com/example/medcarapp/IntroductoryActivity.java
  android/app/src/main/java/com/example/medcarapp/MainActivity.java
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  android/app/src/main/res/anim/splash_animation.xml
  android/app/src/main/res/drawable-v24/carcam.png
  android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/drawable/joystickbg.png
  android/app/src/main/res/drawable/joystickbutton1.png
  android/app/src/main/res/drawable/logo7.png
  android/app/src/main/res/layout/activity_introductory.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/activity_manual_control.xml
  android/app/src/main/res/layout/recycle_view_rows.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/ic_launcher_background.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/themes.xml
  android/app/src/test/java/com/example/medcarapp/ExampleUnitTest.java
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
Labels: Sprint 1

#22 Update android UI
  android/app/src/main/java/com/example/medcarapp/Adapter.java
  android/app/src/main/java/com/example/medcarapp/MainActivity.java
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/credit_popup.xml
  android/app/src/main/res/layout/recycle_view_rows.xml
  android/app/src/main/res/values/colors.xml
Labels: improvement

#23 MQTT Connectivity
  .github/workflows/arduino-build.yml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/medcarapp/MainActivity.java
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  android/app/src/main/java/mqttController/CarConnect.java
  android/app/src/main/java/mqttController/MqttClient.java
  android/build.gradle
  arduino/smartcar/smartcar.ino
Labels: Sprint 2

#24 Manual maneuvering
  android/app/src/main/java/com/example/medcarapp/MainActivity.java
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  android/app/src/main/java/mqttController/CarConnect.java
  arduino/smartcar/smartcar.ino
Labels: Sprint 2

#26 Fix joystick publish spam bug
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
Labels: Bug fix, Sprint 2

#27 Status text when connected to server
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  android/app/src/main/java/mqttController/CarConnect.java
  android/app/src/main/res/layout/activity_manual_control.xml
Labels: Sprint 2

#28 Adds obstacle avoidance to manual control
  android/app/src/main/java/com/example/medcarapp/ManualControl.java
  arduino/smartcar/smartcar.ino
Labels: Sprint 2
